// photo_data.js
// Database of 20 approved, anonymized student bulletin board submissions across Months 1, 2, and 3.

const campusBadges = [
    { id: "badge-1", name: "Sprout Scout", level: "Level 1", icon: "🌱", requirement: "1st Monthly Upload", unlocked: true, unlockedDate: "June 2026", desc: "Campus bulletin board verified active on public dashboard." },
    { id: "badge-2", name: "Canopy Chronicler", level: "Level 2", icon: "🌿", requirement: "3 Monthly Uploads", unlocked: true, unlockedDate: "August 2026", desc: "Seasonal environmental transition logged across Donna & Mercedes ISD." },
    { id: "badge-3", name: "Grove Guardian", level: "Level 3", icon: "🌳", requirement: "6 Monthly Uploads", unlocked: false, unlockedDate: "Target: Nov 2026", desc: "Half-year stewardship milestone unlocked with district ribbon." },
    { id: "badge-4", name: "Ecosystem Champion", level: "Level 4", icon: "🦅", requirement: "10 Monthly Uploads", unlocked: false, unlockedDate: "Target: May 2027", desc: "Full-year academic biodiversity and tree canopy archive completed." },
    { id: "badge-5", name: "Artisan Arborist", level: "Specialty", icon: "🎨", requirement: "10+ Art Submissions", unlocked: true, unlockedDate: "August 2026", desc: "Awarded for exceptional student leaf rubbings, sketches, and poetry." },
    { id: "badge-6", name: "Bio-Detective", level: "Specialty", icon: "🔍", requirement: "5+ Wildlife Species", unlocked: true, unlockedDate: "August 2026", desc: "Awarded for multi-taxa wildlife observations on campus grounds." }
];

const photoData = [
    {
        id: "board-01",
        image: "assets/photo_sapling.jpg",
        subject: "Tree Adoption #104: 'El Gigante Verde'",
        category: "Tree Adoption",
        month: "Month 1 (June 2026)",
        campus: "M. Rivas Primary Academy",
        studentRef: "4th Grade Room 204",
        date: "June 12, 2026",
        notes: "Class Adoption Pledge: 'We adopt Tree Tag #104 (Southern Live Oak). We promise to check its soil moisture every Tuesday and measure its growth every month!'",
        approvedBy: "Lead Science Teacher (ID: 492)",
        tags: ["Adoptions", "Live Oak", "Stewardship"]
    },
    {
        id: "board-02",
        image: "assets/cedar_elm_leaf.jpg",
        subject: "Student Poem: 'Underneath the Shade'",
        category: "Poem & Stories",
        month: "Month 1 (June 2026)",
        campus: "M. Rivas Primary Academy",
        studentRef: "3rd Grade Student Poet",
        date: "June 18, 2026",
        notes: "Poem excerpt pinned to board: \n\n'The Texas sun is big and bright,\nIt bakes the playground blacktop tight.\nBut under our Cedar Elm so tall,\nWe feel no burning heat at all.\nCool green leaves whisper in the breeze,\nThank you, thank you, for our trees!'",
        approvedBy: "Language Arts Lead (ID: 201)",
        tags: ["Poems & Stories", "Creative Writing"]
    },
    {
        id: "board-03",
        image: "assets/live_oak_leaf.jpg",
        subject: "Colored Leaf Rubbing: Live Oak Venation",
        category: "Art & Rubbings",
        month: "Month 1 (June 2026)",
        campus: "J.W. Caceres Discovery Intermediate",
        studentRef: "5th Grade Science & Art Cohort",
        date: "June 25, 2026",
        notes: "Wax-crayon rubbing investigation comparing the thick, leathery cuticle of drought-hardy Live Oak leaves against non-native garden foliage.",
        approvedBy: "Art & STEM Teacher (ID: 118)",
        tags: ["Art & Rubbings", "Leaf Rubbings"]
    },
    {
        id: "board-04",
        image: "assets/photo_butterfly.jpg",
        subject: "Wildlife Spotting: Monarch Butterfly Migration",
        category: "Wildlife Spotting",
        month: "Month 1 (June 2026)",
        campus: "Capt. D. Salinas II STEAM",
        studentRef: "Kindergarten Nature Club",
        date: "June 28, 2026",
        notes: "Observation Log: 'I learned this species is a Monarch Butterfly (Danaus plexippus)! It rested on our new native milkweed next to Sapling #12 for 15 minutes.'",
        approvedBy: "Kindergarten Lead (ID: 305)",
        tags: ["Wildlife Spotting", "Insects", "iNaturalist"]
    },
    {
        id: "board-05",
        image: "assets/IMG_7219.jpg",
        subject: "Watering Squad #2: 'Cracker Dirt Test'",
        category: "Stewardship & Care",
        month: "Month 2 (July 2026)",
        campus: "M. Rivas Primary Academy",
        studentRef: "Summer Camp Stewardship Squad",
        date: "July 08, 2026",
        notes: "Field Log: 'We did the SOP dry dirt test. The soil 2 inches down was dry like a cracker! Squad 2 delivered 5 gallons of rainwater from the campus cistern.'",
        approvedBy: "Facilities & Grounds Liaison (ID: 554)",
        tags: ["Stewardship & Care", "Watering Log"]
    },
    {
        id: "board-06",
        image: "assets/realistic_thornscrub.jpg",
        subject: "Colored Drawing: 'Texas Ebony in Bloom'",
        category: "Art & Rubbings",
        month: "Month 2 (July 2026)",
        campus: "Sgt. Manuel Chacon Middle",
        studentRef: "6th Grade Art Class",
        date: "July 15, 2026",
        notes: "Colored pencil illustration detailing the zigzag spiny branches, creamy fragrant blossoms, and thick dark seed pods of native Texas Ebony (Ebenopsis ebano).",
        approvedBy: "Art Teacher (ID: 412)",
        tags: ["Art & Rubbings", "Texas Ebony", "Native Plants"]
    },
    {
        id: "board-07",
        image: "assets/photo_gecko.jpg",
        subject: "Wildlife Spotting: Green Anole on Anacua Bark",
        category: "Wildlife Spotting",
        month: "Month 2 (July 2026)",
        campus: "W.B. Travis Elementary",
        studentRef: "4th Grade Room 108",
        date: "July 22, 2026",
        notes: "Species Log: 'I learned what this lizard is! It is an Anolis carolinensis (Green Anole). It changed from green to brown while hunting ants on Tree #55!'",
        approvedBy: "STEM Specialist (ID: 290)",
        tags: ["Wildlife Spotting", "Reptiles"]
    },
    {
        id: "board-08",
        image: "assets/mesquite_leaf.jpg",
        subject: "Haiku Series: 'Afternoon Mesquite Breeze'",
        category: "Poem & Stories",
        month: "Month 2 (July 2026)",
        campus: "Ruben Hinojosa Elementary",
        studentRef: "5th Grade Dual Language Class",
        date: "July 29, 2026",
        notes: "Bilingual Student Haiku:\n\n'Hojas en el sol (Leaves in the sun),\nBrisa fresca en la tarde (Cool breeze in the afternoon),\nSombra para todos (Shade for everyone).'",
        approvedBy: "Bilingual Educator (ID: 104)",
        tags: ["Poems & Stories", "Bilingual", "Haiku"]
    },
    {
        id: "board-09",
        image: "assets/IMG_7222.jpg",
        subject: "Infrared Heat Hunt: 51°F Cooling Delta!",
        category: "Heat Science",
        month: "Month 3 (August 2026)",
        campus: "M. Rivas Primary Academy",
        studentRef: "5th Grade Science Investigators",
        date: "August 10, 2026",
        notes: "Heat Investigation Results:\n• Unshaded Blacktop: 138.4°F\n• Open Turf in Sun: 114.2°F\n• Soil Under Live Oak Canopy: 87.1°F\nConclusion: 'Our tree canopy creates a 51.3°F cooling shield during afternoon recess!'",
        approvedBy: "Lead Science Teacher (ID: 492)",
        tags: ["Heat Science", "TEKS 5.9A", "Thermography"]
    },
    {
        id: "board-10",
        image: "assets/IMG_7224.jpg",
        subject: "Tree Adoption #78: 'The Elm Street Guardians'",
        category: "Tree Adoption",
        month: "Month 3 (August 2026)",
        campus: "J.W. Caceres Discovery Intermediate",
        studentRef: "5th Grade Student Council",
        date: "August 14, 2026",
        notes: "Adoption Certificate: 'We adopt Cedar Elm Tag #78 near the bus drop-off loop. We will monitor its leaf canopy and ensure no litter collects around the mulch ring.'",
        approvedBy: "Student Council Sponsor (ID: 118)",
        tags: ["Tree Adoption", "Cedar Elm"]
    },
    {
        id: "board-11",
        image: "assets/IMG_7225.jpg",
        subject: "Wildlife Spotting: Green Jay in the Courtyard",
        category: "Wildlife Spotting",
        month: "Month 3 (August 2026)",
        campus: "Patricia S. Garza Elementary",
        studentRef: "3rd Grade Bird Watchers",
        date: "August 17, 2026",
        notes: "Bird Log: 'We spotted a Green Jay (Cyanocorax yncas)! It has bright green wings and yellow tail feathers. It was eating berries from the Anacua tree.'",
        approvedBy: "Science Lead (ID: 610)",
        tags: ["Wildlife Spotting", "Birds", "RGV Natives"]
    },
    {
        id: "board-12",
        image: "assets/tree_roots.jpg",
        subject: "Science Diagram: 'Roots Underground Network'",
        category: "Art & Rubbings",
        month: "Month 3 (August 2026)",
        campus: "Capt. D. Salinas II STEAM",
        studentRef: "4th Grade Soil Science Lab",
        date: "August 19, 2026",
        notes: "Student cross-section drawing illustrating how taproots anchor the tree against tropical windstorms and how root hairs absorb 450 gallons of stormwater runoff.",
        approvedBy: "Science Specialist (ID: 305)",
        tags: ["Art & Rubbings", "Root Architecture", "Stormwater"]
    },
    {
        id: "board-13",
        image: "assets/IMG_7226.jpg",
        subject: "Student Story: 'The Day the Cicadas Sang'",
        category: "Poem & Stories",
        month: "Month 3 (August 2026)",
        campus: "Daniel Singleterry Senior Elementary",
        studentRef: "4th Grade Creative Writing Cohort",
        date: "August 20, 2026",
        notes: "Micro-Story: 'During outdoor reading time, we sat with our backs against the trunk of Tree #19. Suddenly, a choir of cicadas started singing above us in the canopy. It sounded like the tree was humming to keep us cool.'",
        approvedBy: "Instructional Coach (ID: 419)",
        tags: ["Poems & Stories", "Micro-Stories"]
    },
    {
        id: "board-14",
        image: "assets/IMG_7228.jpg",
        subject: "Tree Caliper Growth Log (0.6 Inch Expansion)",
        category: "Heat Science",
        month: "Month 3 (August 2026)",
        campus: "Sgt. William G. Harrell Elementary",
        studentRef: "5th Grade Math & Science Team",
        date: "August 21, 2026",
        notes: "Data Record: 'We measured trunk circumference with the blue tape. Baseline June DBH was 3.2 inches. August DBH is 3.8 inches. That is +0.6 inches of trunk growth in 60 days!'",
        approvedBy: "Math Coach (ID: 512)",
        tags: ["Heat Science", "Tree Caliper", "Math TEKS"]
    },
    {
        id: "board-15",
        image: "assets/IMG_7229.jpg",
        subject: "Split Drawing: 'Playground Heat vs Shade Oasis'",
        category: "Art & Rubbings",
        month: "Month 3 (August 2026)",
        campus: "C. Stainke Intermediate",
        studentRef: "4th Grade Art & Health Class",
        date: "August 22, 2026",
        notes: "Split drawing comparison: Left half shows an unshaded red-hot slide with thermometer at 140°F; Right half shows green tree canopy with children reading on picnic blankets.",
        approvedBy: "Art Educator (ID: 334)",
        tags: ["Art & Rubbings", "Health & Shade"]
    },
    {
        id: "board-16",
        image: "assets/IMG_7230.jpg",
        subject: "Wildlife Spotting: Texas Spiny Lizard on Oak Bark",
        category: "Wildlife Spotting",
        month: "Month 3 (August 2026)",
        campus: "A.M. Ochoa Primary",
        studentRef: "2nd Grade Explorer Squad",
        date: "August 24, 2026",
        notes: "Observation: 'We found a Texas Spiny Lizard (Sceloporus olivaceus). Its rough gray scales matched the Live Oak bark perfectly so birds couldn't see it!'",
        approvedBy: "Primary Science Lead (ID: 220)",
        tags: ["Wildlife Spotting", "Reptiles", "Camouflage"]
    },
    {
        id: "board-17",
        image: "assets/IMG_7231.jpg",
        subject: "Bark Texture Study: Retama Photosynthesis",
        category: "Art & Rubbings",
        month: "Month 3 (August 2026)",
        campus: "A.P. Solis Middle School",
        studentRef: "7th Grade Life Sciences Cohort",
        date: "August 25, 2026",
        notes: "Charcoal bark rubbing and microscope study demonstrating green chlorophyll pigments inside Retama (Parkinsonia aculeata) bark that allow the tree to photosynthesize even without leaves.",
        approvedBy: "Middle School Science Chair (ID: 702)",
        tags: ["Art & Rubbings", "Retama", "Botany"]
    },
    {
        id: "board-18",
        image: "assets/IMG_7232.jpg",
        subject: "Tree Adoption #212: 'Baby Oak Charlie'",
        category: "Tree Adoption",
        month: "Month 3 (August 2026)",
        campus: "Mercedes Academic Academy",
        studentRef: "High School Environmental Science Leaders",
        date: "August 25, 2026",
        notes: "Mentorship Adoption: 'High school students partnered with kindergarten buddies to adopt Mexican White Oak Tag #212. We installed a drip bag and tagged the perimeter with reflective stones.'",
        approvedBy: "Academy Director (ID: 881)",
        tags: ["Tree Adoption", "Mentorship", "Oak"]
    },
    {
        id: "board-19",
        image: "assets/waterharvesting.jpg",
        subject: "Cistern Flow Investigation: 350 Gal Harvested",
        category: "Stewardship & Care",
        month: "Month 3 (August 2026)",
        campus: "W.B. Travis Elementary",
        studentRef: "Green Ambassadors Club",
        date: "August 26, 2026",
        notes: "Rainwater Harvesting Log: 'After Tuesday afternoon tropical downpour, the school roof collected 350 gallons of rainwater in the green cistern. We used it to deep-water all 24 new saplings!'",
        approvedBy: "Sustainability Coordinator (ID: 190)",
        tags: ["Stewardship & Care", "Water Harvesting"]
    },
    {
        id: "board-20",
        image: "assets/year_10_mature.png",
        subject: "Vision Collage: 'Our School Forest in 2040'",
        category: "Art & Rubbings",
        month: "Month 3 (August 2026)",
        campus: "M. Rivas Primary Academy",
        studentRef: "Collective All-School Art Mural",
        date: "August 26, 2026",
        notes: "All-school time-lapse collage: Student drawings showing how our saplings will grow into a connected shade canopy by 2040 when today's 4th graders are graduating college!",
        approvedBy: "Campus Principal & Art Committee (ID: 492)",
        tags: ["Art & Rubbings", "Time Machine", "2040 Vision"]
    }
];
